"""Class scaffolding for the MLB Player Guessing Game.

See Design.md for the full design. The dataset (Data/MLB_2025) is used ONLY to
pick the secret player. All clues are generated by GeminiModel and screened by
ValidatorModel so a clue never leaks the player's name.

Classes:
    Player          - a single MLB player (name / team / position)
    GeminiModel     - thin wrapper around the Gemini API
    ValidatorModel  - detects name leaks and builds corrective re-prompts
    Clue            - owns the 3 fixed clue questions + the validated clue loop
    Game            - orchestrates a round: pick player, reveal clues, score
"""

from __future__ import annotations

import json
import os
import random
from dataclasses import dataclass, field


# ---------------------------------------------------------------------------
# Config
# ---------------------------------------------------------------------------

DATA_PATH = os.path.join(os.path.dirname(__file__), "Data", "MLB_2025")


def _load_env(path: str = ".env") -> dict:
    """Read a simple KEY = VALUE .env file (values may have surrounding spaces)."""
    env = {}
    full = os.path.join(os.path.dirname(__file__), path)
    if not os.path.exists(full):
        return env
    with open(full, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#") or "=" not in line:
                continue
            key, value = line.split("=", 1)
            env[key.strip()] = value.strip()
    return env


# ---------------------------------------------------------------------------
# Player
# ---------------------------------------------------------------------------


def decode_name(name) -> str:
    """Normalize a player name that may carry UTF-16 encoding artifacts.

    Source rows sometimes arrive with the name still UTF-16 encoded (raw bytes)
    or with lingering surrogate code points from a bad decode. This coerces
    such values back to a clean Python str; already-clean names pass through
    unchanged.
    """
    if name is None:
        return ""
    # Raw bytes: use the BOM to pick UTF-16, else UTF-8. (Auto-guessing UTF-16
    # vs UTF-8 without a BOM is unreliable — UTF-16 "succeeds" on UTF-8 bytes
    # and yields garbage — so we only treat BOM-prefixed data as UTF-16.)
    if isinstance(name, (bytes, bytearray)):
        data = bytes(name)
        if data[:2] in (b"\xff\xfe", b"\xfe\xff"):
            name = data.decode("utf-16")
        else:
            name = data.decode("utf-8", errors="replace")
    # Repair any unpaired/paired surrogate code points left in a str by
    # re-encoding as UTF-16 and decoding back.
    if isinstance(name, str) and any(0xD800 <= ord(ch) <= 0xDFFF for ch in name):
        name = name.encode("utf-16", "surrogatepass").decode("utf-16")
    return name


@dataclass
class Player:
    """A single MLB player. Only identity fields are used by the game."""

    name: str
    team: str = ""
    position: str = ""
    war: float | None = None
    age: int | None = None
    awards: str = ""
    games: int | None = None
    home_runs: int | None = None
    batting_avg: float | None = None
    on_base_pct: float | None = None
    slugging: float | None = None
    ops: float | None = None

    @classmethod
    def from_record(cls, record: dict) -> "Player":
        """Build a Player from one row of Data/MLB_2025."""
        return cls(
            name=decode_name(record.get("Player", "")),
            team=record.get("Team", ""),
            position=record.get("Pos", ""),
            war=record.get("WAR"),
            age=record.get("Age"),
            awards=record.get("Awards", ""),
            games=record.get("G"),
            home_runs=record.get("HR"),
            batting_avg=record.get("BA"),
            on_base_pct=record.get("OBP"),
            slugging=record.get("SLG"),
            ops=record.get("OPS"),
        )


# ---------------------------------------------------------------------------
# GeminiModel
# ---------------------------------------------------------------------------


class GeminiModel:
    """Thin wrapper around the Gemini API used to retrieve clue text.

    Pulls facts about a player from outside our dataset.
    """

    def __init__(self, api_key: str | None = None, model_name: str | None = None):
        env = _load_env()
        self.api_key = api_key or env.get("API_KEY", "")
        self.model_name = model_name or env.get("GEMINI_MODEL", "gemini-3.6-flash")
        self._client = None  # lazy-initialized google.genai Client

    def _get_client(self):
        """Lazily create the genai client (kept out of __init__ for testability)."""
        if self._client is None:
            from google import genai

            self._client = genai.Client(api_key=self.api_key)
        return self._client

    def ask(self, prompt: str) -> str:
        """Send a prompt to Gemini and return the text response."""
        client = self._get_client()
        resp = client.models.generate_content(
            model=self.model_name, contents=prompt
        )
        return (resp.text or "").strip()


# ---------------------------------------------------------------------------
# ValidatorModel
# ---------------------------------------------------------------------------


class ValidatorModel:
    """Guards clues against leaking the player's name.

    On a leak, builds an explicit corrective prompt that re-prompts Gemini,
    naming the offending information and forbidding it.
    """

    def __init__(self, max_retries: int = 3):
        self.max_retries = max_retries

    def contains_name(self, clue_text: str, player_name: str) -> bool:
        """Return True if the clue leaks the player's name (full or any part).

        TODO: refine matching (accents, nicknames). Baseline: case-insensitive
        substring match on the full name and each name token.
        """
        if not clue_text or not player_name:
            return False
        text = clue_text.lower()
        if player_name.lower() in text:
            return True
        for token in player_name.lower().split():
            if len(token) > 2 and token in text:
                return True
        return False

    def build_correction_prompt(
        self, question: str, player_name: str, bad_answer: str
    ) -> str:
        """Build an explicit re-prompt telling Gemini not to mention the name."""
        return (
            "Your previous answer mentioned the player's name, which is not "
            f"allowed. Do NOT include '{player_name}' or any part of it.\n"
            f"Previous answer: {bad_answer}\n"
            f"Answer this question again without revealing the name: {question}"
        )

    @staticmethod
    def redact_name(clue_text: str, player_name: str) -> str:
        """Last-resort fallback: blank out the name if retries are exhausted."""
        result = clue_text
        for token in [player_name, *player_name.split()]:
            if len(token) > 2:
                result = result.replace(token, "[hidden]")
        return result


# ---------------------------------------------------------------------------
# Clue
# ---------------------------------------------------------------------------


class Clue:
    """Owns the 3 fixed clue questions and the validated clue loop."""

    # Short UI labels, index-aligned with CLUE_QUESTIONS below.
    CLUE_LABELS = [
        "Player Nickname",
        "College / High School",
        "Best Career Moment",
    ]

    CLUE_QUESTIONS = [
        "Does the player have a nickname? If so, what is it?",
        "What college or high school did the player attend?",
        "What is the player's best career moment?",
    ]

    def __init__(
        self,
        player: Player,
        gemini: GeminiModel | None = None,
        validator: ValidatorModel | None = None,
    ):
        self.player = player
        self.gemini = gemini or GeminiModel()
        self.validator = validator or ValidatorModel()

    def _build_prompt(self, question: str) -> str:
        """Compose the base prompt for a clue question."""
        return (
            f"You are giving a trivia clue about the MLB player {self.player.name}. "
            "Answer the following question factually and concisely. "
            f"Do NOT mention the player's name.\nQuestion: {question}"
        )

    def get_validated_clue(self, index: int) -> str:
        """Get clue `index`, re-prompting until the name is absent (Design.md loop).

        TODO: wire up once GeminiModel.ask is implemented.
        """
        question = self.CLUE_QUESTIONS[index]
        prompt = self._build_prompt(question)

        answer = self.gemini.ask(prompt)
        retries = 0
        while (
            self.validator.contains_name(answer, self.player.name)
            and retries < self.validator.max_retries
        ):
            correction = self.validator.build_correction_prompt(
                question, self.player.name, answer
            )
            answer = self.gemini.ask(correction)
            retries += 1

        if self.validator.contains_name(answer, self.player.name):
            answer = self.validator.redact_name(answer, self.player.name)
        return answer


# ---------------------------------------------------------------------------
# Game
# ---------------------------------------------------------------------------


@dataclass
class Game:
    """Orchestrates one round: pick a secret player, reveal clues, score guesses."""

    data_path: str = DATA_PATH
    player_data: list = field(default_factory=list)
    all_names: list = field(default_factory=list)
    secret_player: Player | None = None
    clue: Clue | None = None
    clue_index: int = 0
    attempts: int = 0
    score: int = 0
    status: str = "playing"  # "playing" | "won" | "lost"

    MAX_CLUES = 3

    def __post_init__(self):
        if not self.player_data:
            self.load_data()

    def load_data(self) -> None:
        """Load Data/MLB_2025 into a list of records and cache all player names."""
        with open(self.data_path, "r", encoding="utf-8") as f:
            raw = json.load(f)
        self.player_data = list(raw.values())
        self.all_names = sorted(r.get("Player", "") for r in self.player_data)

    def all_teams(self) -> list:
        """Return the sorted unique team codes present in the data.

        A player's Team field may list several space-separated codes (traded
        mid-season, e.g. "BOS SFG"), so codes are split out individually.
        """
        codes = set()
        for record in self.player_data:
            codes.update(record.get("Team", "").split())
        return sorted(codes)

    def retrieve_player(
        self, team: str | None = None, awards: bool = False
    ) -> Player:
        """Pick a random secret player from the data.

        Optional filters:
            team    - only players whose Team field contains this team code.
            awards  - if truthy, only players with "AS" in their Awards field
                      (i.e. All-Stars).
        """
        candidates = self.player_data
        if team:
            candidates = [r for r in candidates if team in r.get("Team", "")]
        if awards:
            candidates = [r for r in candidates if "AS" in r.get("Awards", "")]

        if not candidates:
            raise ValueError("No players match the given filters.")

        record = random.choice(candidates)
        self.secret_player = Player.from_record(record)
        return self.secret_player

    def retrieve_guess(self, name: str) -> Player | None:
        """Look up a player by name and return a Player object.

        Unlike retrieve_player, this does NOT set self.secret_player. Returns
        None if no player with a matching name is found. Matching is
        case-insensitive on the full name.
        """
        target = name.strip().lower()
        for record in self.player_data:
            if record.get("Player", "").strip().lower() == target:
                return Player.from_record(record)
        return None

    def start_new_round(self, team: str | None = None, awards: bool = False) -> None:
        """Reset state and begin a new round.

        Filters (team, awards) are forwarded to retrieve_player to constrain
        which players can be chosen as the secret.
        """
        self.retrieve_player(team=team, awards=awards)
        self.clue = Clue(self.secret_player)
        self.clue_index = 0
        self.attempts = 0
        self.status = "playing"

    def get_clue(self, index: int) -> str:
        """Return the clue at a specific index (0-based), independent of order.

        Used when clues can be revealed individually rather than sequentially.
        """
        if index < 0 or index >= self.MAX_CLUES:
            return None
        return self.clue.get_validated_clue(index)

    def next_clue(self) -> str:
        """Return the next clue in sequence, or None if all are exhausted."""
        if self.clue_index >= self.MAX_CLUES:
            return None
        clue_text = self.clue.get_validated_clue(self.clue_index)
        self.clue_index += 1
        return clue_text

    def check_guess(self, name: str) -> bool:
        """Check a guessed name against the secret. Advances/ends the round.

        Clues are now revealed independently of guessing, so the round ends
        after MAX_CLUES wrong *attempts* rather than after all clues are used.
        Scoring still rewards guessing with fewer clues revealed.
        """
        self.attempts += 1
        correct = name.strip().lower() == self.secret_player.name.strip().lower()
        if correct:
            self.status = "won"
            self.score += self._score_for_clues_used()
        elif self.attempts >= self.MAX_CLUES:
            self.status = "lost"
        return correct

    def _score_for_clues_used(self) -> int:
        """Fewer clues used = more points."""
        return max(10, 100 - 30 * self.clue_index)

    def end_round(self) -> None:
        """Force-end the round (e.g. give up)."""
        self.status = "lost"


if __name__ == "__main__":
    # Smoke test the data-driven parts (no Gemini calls).
    g = Game()
    print(f"Loaded {len(g.player_data)} players.")
    g.start_new_round()
    print(f"Secret player: {g.secret_player}")
    print(f"Clue questions: {Clue.CLUE_QUESTIONS}")
